# Generated by Django 2.1.5 on 2019-02-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0002_auto_20190203_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=459),
        ),
    ]
