# Generated by Django 2.1.5 on 2019-02-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0003_auto_20190203_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
