# Generated by Django 2.1 on 2019-04-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0003_auto_20190411_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='case',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='case',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='availability',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
