# Generated by Django 2.1 on 2019-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0005_auto_20190414_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Haemoglobin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_presure',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='patient_icon.png', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sugar',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
