# Generated by Django 2.1.5 on 2019-03-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0005_auto_20190210_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
