# Generated by Django 2.1 on 2019-04-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0006_auto_20190415_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(default='doc_male.png', upload_to='img/'),
        ),
    ]
