# Generated by Django 2.1 on 2019-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0007_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(default='doc_male.png', upload_to='doctorfinder/img/'),
        ),
    ]
