# Generated by Django 2.1 on 2019-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0009_doctor_about_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(default='doc_male.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='/patient_icon.png', upload_to='img/'),
        ),
    ]
