# Generated by Django 2.1 on 2019-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0010_auto_20190427_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='sampleupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_file', models.FileField(upload_to='')),
            ],
        ),
    ]
