# Generated by Django 2.1.5 on 2019-05-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0011_sampleupload'),
        ('doctorfinder', '0006_case_status'),
    ]

    operations = [
    ]
