# Generated by Django 2.1.5 on 2019-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0012_merge_20190504_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sampleupload',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='type',
            new_name='availability_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='case_id',
        ),
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.FileField(default='doc_male.png', upload_to='doctorfinder/img/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='patient_icon.png', upload_to='doctorfinder/img/'),
        ),
    ]
