# Generated by Django 2.1.5 on 2019-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0013_auto_20190618_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='availability_type',
        ),
    ]
