# Generated by Django 2.1.5 on 2019-06-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0015_auto_20190619_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctorfinder.availability'),
        ),
    ]
