# Generated by Django 2.1.5 on 2019-06-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorfinder', '0016_auto_20190619_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
    ]
